### ISSUE TITLE
Datepicker is not keyboard accessible in certain cases

### ISSUE THREAD

**Issue by mcmxcdev** [mantinedev/mantine#1698]
### What package has an issue

@mantine/dates

### Describe the bug

I discovered through writing an e2e test that `Datepicker` component with `allowFreeInput` prop is not keyboard accessible.

You can verify this by going to e.g. https://v5.mantine.dev/dates/date-picker/#min-and-max-dates and checking the following examples:

- Min and max dates
- Allow free input
- Styles based on modifiers

Try to use `arrow down` or `tab` key, and you should see that these examples are not keyboard accessible like the other examples. 

All others work as expected.

### In which browser did the problem occur

Brave Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It works as expected – when you set `allowFreeInput` you expect users with keyboards to enter date in the input. When `allowFreeInput={false}` then user can use keyboard to select the date with arrow keys and Enter.

**Comment by mcmxcdev** [comment]
I understand. Why can't it be both? Users might still want the option between navigating with arrow keys or entering text in the input.

And what about the other examples on the website that don't even use `allowFreeInput` prop?

**Comment by rtivital** [comment]
Fixed in 4.2.12

**Comment by mcmxcdev** [comment]
I had another look at this and it seems that "Min and max dates" and "Styles based on modifiers" examples now are keyboard accessible, but https://mantine.dev/dates/date-picker/#allow-free-input still isn't.

Is this expected because users are supposed to enter it into the text field? Can't they both be enabled to type OR tab through the calendar?
