### ISSUE TITLE
Upgrading the dependency version of @mantine/core, @mantine/dates to 5.10.5 removes @floating-ui/react-dom from package-lock and breaks the datepicker input

### ISSUE THREAD

**Issue by daksh-sagar** [mantinedev/mantine#3647]
### What package has an issue

@mantine/dates @mantine/core

### Describe the bug

i made updates to dep version of packages as show in the `package.json` diff below

<img width="1328" alt="package-json diff" src="https://user-images.githubusercontent.com/24277216/222418523-a305aac7-3093-4c27-a442-4edcd3e237ea.png">
Post the update, the datepicker input in my app stopped working on **chrome mobile** and **safari mobile** (although it works on **desktop browsers**) where clicking on the datepicker input freezes the tab without datepicker ever opening.      

##

I had a look at the `package-lock.json` and the diff shows that @floating-ui/react-dom and related packages to be removed form `package-lock`. Since  `@floating-ui` deals with showing menus, popovers, etc, I feel that issue is probably happening because of this peer dependency being removed from `package-lock`.     
    
##

<img width="1247" alt="package-lock diff" src="https://user-images.githubusercontent.com/24277216/222418561-648e3445-b7e2-4a8c-90f2-7e229bd7ca3c.png">

##
**This issue gets resolved when i revert the version upgrade.**

##

I've seen [this issue](https://github.com/mantinedev/mantine/issues/3376) where it mentions that `@floating-ui/react-dom-interactions` has been deprecated and hence removed, but i'm not sure why `@floating-ui/react-dom` got removed as well.

### What version of @mantine/hooks page do you have in package.json?

5.10.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Mantine packages now use `"@floating-ui/react": "^0.19.1",` package. `@floating-ui/react-dom` is a dependency of `@floating-ui/react` as seen here – https://www.npmjs.com/package/@floating-ui/react?activeTab=dependencies

**Comment by daksh-sagar** [comment]
alright, so is `@floating-ui/react-dom` getting removed from package-lock the expected behaviour ?

**Comment by rtivital** [comment]
I do not know, try reinstalling dependencies

**Comment by mcmxcdev** [comment]
@daksh-sagar For us, it does work as expected. What I am posting is a pnpm lockfile, so not npm, but it shouldn't matter. 

`@mantine/core` has a dependency on `@floating-ui/react` set correctly, so there should be nothing necessary to do on your end since `npm i` should resolve it:

![image](https://user-images.githubusercontent.com/16797721/222651480-259ad3a8-42af-4a93-b3e3-5e66c312baae.png)

**Comment by daksh-sagar** [comment]
@mcmxcdev thanks for the response : ). I've tried running npm i again but the issue still persists. I'll try it again once, and i'll post here if i find any solution or cause of the issue

**Comment by gregrickaby** [comment]
👋🏻 Ran into the same issue this morning when upgrading to Mantine v6. For context, I'm using NPM Workspaces.

I had to delete _all_ the `node_modules` directories scattered throughout my workspaces _and_ the `package.lock` at the root. Then  `npm i`

I believe the issue was a `node_modules` folder inside one of my workspaces already had `@mantine` package, so for whatever reason, NPM wouldn't install these `@mantine/core` dependencies:

```json
    "node_modules/@mantine/core": {
      "version": "6.0.0",
      "resolved": "https://registry.npmjs.org/@mantine/core/-/core-6.0.0.tgz",
      "integrity": "sha512-ik2NUAAn9fYcqmOAluGtI9R73ijrr450dZDA+MezKq/dvpUU/Fhl9yXnGoCxxZ5XF6y4i6q07318rdrVturc9w==",
      "dependencies": {
        "@floating-ui/react": "^0.19.1",
        "@mantine/styles": "6.0.0",
        "@mantine/utils": "6.0.0",
        "@radix-ui/react-scroll-area": "1.0.2",
        "react-remove-scroll": "^2.5.5",
        "react-textarea-autosize": "8.3.4"
      },
    },
```

Hope this helps!

**Comment by daksh-sagar** [comment]
Hey @gregrickaby, thanks for the response :) 
I'm using npm workspaces too (along with turborepo, but  i'm not sure whether deleting `package.lock` is a good idea.

**Comment by gregrickaby** [comment]
@daksh-sagar I'm also using Turborepo in [my project](https://github.com/gregrickaby/nextjs-wordpress) and I've had no issues deleting the `package.lock`. NPM reads `package.json` and generates `package.lock` each time you run `npm i`.

The issue I ran into was probably caused by me accidently running `npm i` inside `/apps/nextjs` instead of at the root. This generated a `node_modules` directory inside `/apps/nextjs/` which messed with the Workspace.

**Comment by arpitprod** [comment]
I am also facing this issue after upgrade from 5.10.3

**Comment by arpitprod** [comment]
My react page is freezing when I click inside date picker after upgrade from 5.10.3 and I am unable to debug also because of freezing

**Comment by cyantree** [comment]
Can you please open a separate issue for this?
Maybe it's related to #3643. Check whether your date picker has enough space above and below which might prevent the issue.

**Comment by arpitprod** [comment]
yes @cyantree , I am facing same issue, thanks
