### ISSUE TITLE
Dropzone dnd is buggy

### ISSUE THREAD

**Issue by D3kion** [mantinedev/mantine#4934]
### What package has an issue

@mantine/dropzone

### Describe the bug

When dragging file onto dropzone it works correct only on outter paddings

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0 but tested in 7.1 too

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Locally fixed version from Mantine-ui with `.mantine-Dropzone-inner { pointer-events: none }`, but i think that's not specific to component from Mantine-ui

**Comment by rtivital** [comment]
Please provide a reproduction (video) or sandbox with steps to reproduce. It is not clear what the issue is based on the issue description.

**Comment by D3kion** [comment]
Sry but i'm lazy:D
Try to move file to dropzone

**Comment by D3kion** [comment]
Tested only on latest versions of Chrome btw

**Comment by D3kion** [comment]
Yo, seems like dropzone now is completly broken
Haven't tested locally, but in docs dnd isn't working at all, and any upload results error in console

**Comment by DenisBessa** [comment]
> Yo, seems like dropzone now is completly broken Haven't tested locally, but in docs dnd isn't working at all, and any upload results error in console

Yeah, same here.

**Comment by joao-vasconcelos** [comment]
Hey! I'm getting this error when following the docs:

```
TypeError: attr_accept__WEBPACK_IMPORTED_MODULE_0__ is not a function
    at A (webpack-internal:///(app-pages-browser)/./node_modules/react-dropzone-esm/dist/esm/utils.mjs:29:959)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/react-dropzone-esm/dist/esm/index.mjs:12:6515)
    at Array.forEach (<anonymous>)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/react-dropzone-esm/dist/esm/index.mjs:12:6436)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/react-dropzone-esm/dist/esm/index.mjs:12:7515)
```

**Comment by rtivital** [comment]
Both issues are resolved in [7.1.2](https://github.com/mantinedev/mantine/releases/tag/7.1.2)

**Comment by D3kion** [comment]
Thanks a lot!

**Comment by joao-vasconcelos** [comment]
Thank you!

**Comment by alesh-kajzar** [comment]
Looks like this is still an issue in 7.1.5. When a file is dragged above inner element (e.g.<Text>), dropzone looks like in Idle state. It is only visual bug, the dropzone still accepts the file. @D3kion image shows it perfectly:

![](https://user-images.githubusercontent.com/21011899/271825992-ed3b292b-fa4d-4cfb-b6e7-e48c9fa21643.png)
