### ISSUE TITLE
Opening a Menu logs error in console

### ISSUE THREAD

**Issue by ShadowWolf308** [mantinedev/mantine#6644]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

On opening a menu an error gets logged in the console as follows:

```
Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. <div tabindex=​"-1" data-autofocus=​"true" aria-hidden=​"true" style=​"outline:​ 0px;​">​</div>​
```

### If possible, include a link to a codesandbox with a minimal reproduction

This can be reproduced in the [mantine.dev](https://mantine.dev/core/menu/) site

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.12.2](https://github.com/mantinedev/mantine/releases/tag/7.12.2)

**Comment by Jannchie** [comment]
It seems to not have been fixed. Clicking “toggle menu” twice still triggers this issue. Additionally, in my local project, clicking once still triggers this issue as well. I am using version 7.12.2.

**Comment by rtivital** [comment]
I do not get any errors in console on mantine.dev website.

**Comment by Jannchie** [comment]
https://github.com/user-attachments/assets/8825cf88-245c-480e-85e9-fe46aa0c3119

**Comment by JonatanRydh** [comment]
This is still an issue. One way to reproduce on mantine.dev:

1. Go to https://mantine.dev/core/menu/
2. Open developer console, make sure it is docked in the same window.
3. Resize the developer console.
4. Click "Toggle menu" twice.

**Comment by felixmueller-cnnctvstn** [comment]
yes, can confirm this error persists...
