### ISSUE TITLE
Page freeze when using Select

### ISSUE THREAD

**Issue by mjsgit870** [mantinedev/mantine#7999]
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

8.1.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome, Brave, Microsoft Edge

### Describe the bug

the page always freezes especially when scrolling on pages that use Select, even the Select documentation page also freezes when scrolling.

I've tried several browsers

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by famasya** [comment]
There might be a bug according to this discussion: https://discord.com/channels/854810300876062770/1381804746993700904

Possible workaround:
1. Downgrade to 8.0.2
2. Use `patch` from this PR https://github.com/mantinedev/mantine/pull/7983

I personally use option 1 to solve this issue.

**Comment by mjsgit870** [comment]
@famasya thanks man

**Comment by WojakGra** [comment]
I just had the same problem and found this issue https://github.com/mantinedev/mantine/issues/6771 and on the new version(8.1.1) still persists https://codesandbox.io/p/devbox/mantine-react-template-forked-zyjhrt

**Comment by pavelcerveny** [comment]
@famasya tried your workaround but even on 8.0.2 the issue still persists

**Comment by WojakGra** [comment]
> [@famasya](https://github.com/famasya) tried your workaround but even on 8.0.2 the issue still persists

https://codesandbox.io/p/devbox/mantine-react-template-forked-zyjhrt
Try this because i had the same problem with Select component. I found an old issue that made the problem gone with keepMounted and forked it to see if 8.1.1 is working well

**Comment by JuanAntonioV** [comment]
I found a way to solve that problem. Try adding `keepMounted: false` inside `comboboxProps` of `Select` component. 

Work on `8.1.1`

```
<Select
  label='Area Location'
  searchable
  comboboxProps={{
    keepMounted: false,
  }}
  data={[]}
/>
```

**Comment by rtivital** [comment]
Fixed in [8.1.2](https://github.com/mantinedev/mantine/releases/tag/8.1.2)

**Comment by henrikwirth** [comment]
While this seems to fix the issue for scrolling, I have a dynamic list where a big list of items (including a Select component) crashes the browser when I reorder components. Obviously this triggers a re-render and for some reason it only crashed if a Select component is present. If I am using `Menu` instead with the exact same setup, I have no issues at all. 

Edit: Seems like using `comboboxProps={{ keepMounted: false }}` helps to mitigate the issue. Though I am wondering why this is not the default similar to how it is on `Menu`

**Comment by LShuXin** [comment]
> I found a way to solve that problem. Try adding `keepMounted: false` inside `comboboxProps` of `Select` component.
> 
> Work on `8.1.1`
> 
> ```
> <Select
>   label='Area Location'
>   searchable
>   comboboxProps={{
>     keepMounted: false,
>   }}
>   data={[]}
> />
> ```

I am using 8.1.0, this solved my problem

**Comment by sunknudsen** [comment]
Hey @rtivital, I believe issue is still present in version 8.3.8 on Ubuntu 24.04.3 (everything works fine on macOS 15.7.2 which is strange).

I am developing an Electron app and without `keepMounted: false`, app hangs as soon as I click on Select component.
