### ISSUE TITLE
`<DateInput>`'s `allowDeslect` property is not respected

### ISSUE THREAD

**Issue by HelloItsKarina** [mantinedev/mantine#8229]
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

8.2.8

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Hiya, thanks for making such a great UI library!

I'm wondering whether I misunderstand the documentation or have found a bug.

Here I backspace the value in an uncontrolled `<DateInput>`, then blur the input. As expected, the input reverts to its previous value.
![Image](https://github.com/user-attachments/assets/da7ffde3-39c3-48d5-8bb1-55d52535de30)

I want the input to remain empty after I backspace its value. If I correctly understand [the docs](https://mantine.dev/dates/date-input/?t=props), then the `allowDeselect` prop should facilitate this.
<img width="2242" height="336" alt="Image" src="https://github.com/user-attachments/assets/26764116-979f-4b1a-9818-405207e67940" />

But `<DateInput allowDeselect>` appears to behave no differently. I also tried `<DateInput allowDeselect={true}>`, which I understand to be equivalent. But no dice.

[The docs](https://mantine.dev/dates/date-input/?t=props) further explain that I should be able to deselect the value by clicking the currently-selected date in the calendar popover. This behaviour also appears missing:
![Image](https://github.com/user-attachments/assets/dcc8027c-ac22-4e71-8036-1da5453bcdb3)

Is this a bug? Or do I misunderstand the documentation?

### Why not use `<DateInput clearable>`?
Because my feature uses the input's `rightSection` for other things.
### Whatever you pass as `rightSection` will overwrite `clearable`'s "X" icon
Yes, but in particular I'm using `rightSection` to represent loading states and other feedback. I only use `rightSection` some of the time. So the pesky "X" icon appears during the times when I'm not overwriting `rightSection`.
### Why not pass `rightSection={isLoading ? '...' : null}`?
Because both `null` and `undefined` are interpreted by `<DateInput>` to mean _show the "X" icon_. 😓

For now, I'm working around this issue by passing `clearable` in conjunction with a bunch of ternaries that set `rightSectionWidth={0}` during the times when I'm passing `rightSection={null}`.

Thanks in advance for your clarification or fix! 🙏

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [8.3.1](https://github.com/mantinedev/mantine/releases/tag/8.3.1)

**Comment by HelloItsKarina** [comment]
Hi, @rtivital.

✅ Having upgraded to 8.3.1, I can confirm that I'm now able to clear `<DateInput allowDeselect>`'s value by clicking the currently-selected date in the calendar popover.

![Image](https://github.com/user-attachments/assets/97c72e87-a4bf-4be7-a089-3edf2dc7a9c2)

❌ But I'm still unable to clear `<DateInput allowDeselect>`'s value by backspacing within the input. The input still reverts to its previous value on blur.

![Image](https://github.com/user-attachments/assets/65eb8e87-5d71-4cbd-bc25-4403e5eaa3e7)

**Comment by rtivital** [comment]
Okay, I'll have a look if this can be fixed in the next patch release

**Comment by rtivital** [comment]
I've updated the logic to allow clearing the value by clearing the input. The fix will be available in 8.3.2 patch.

**Comment by HelloItsKarina** [comment]
Thank you very much, @rtivital! 🙏 Can confirm that it's working great now.
